### ISSUE TITLE
resource_subject missing

### ISSUE THREAD

**Issue by eneasz** [OneMount/terraform-provider-confluent#1]
Hi!

Many thanks for your work and publishing it, one thing I notice is missing and should be easy to add is resource subject, currently role binding is limited to the resource type topic, subject is close but is base on schema registry example:

confluent iam rolebinding create \
--principal User:sam \
--resource Subject:transactions \
--prefix \
--role ResourceOwner \
--kafka-cluster-id my-kafka-cluster-ID \
--schema-registry-cluster-id schema-registry-cool-cluster

The schema is needed when for example using Avro messages.

**Comment by wayarmy** [comment]
Thanks for your contribution, and so sorry for my late reply. At the moment, i'm working on it to add full resource types like Subject and Schema, will public asap @eneasz.

**Comment by wayarmy** [comment]
@eneasz i've just add features to support all kinds of `resources types`, not only `topic`. Please take a look into [new release](https://github.com/OneMount/terraform-provider-confluent/releases/tag/v0.1.1)
